### ISSUE TITLE
Unhandled Exception in /s/12242141

### ISSUE THREAD

**Issue by batflyer** [batflyer/FanFiction-Collaborative-Filtering#3]
Currently an exception is raised when parsing the contents of /s/12242141, resulting in remaining sids being dumped to a file.

Produced with:
```
$ echo "12242141" > sid.txt
$ python scraper/Scraper.py -f sid.txt
```

**Comment by batflyer** [comment]
Looks like this is specific to stories with large numbers of reviews.

```bash
Traceback (most recent call last):
  File "/home/batflyer/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/batflyer/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/batflyer/FanFiction-Collaborative-Filtering/ffscraper/__main__.py", line 68, in <module>
    current_story = story.scraper(args.sid)
  File "/home/batflyer/FanFiction-Collaborative-Filtering/ffscraper/fanfic/story.py", line 159, in scraper
    num_of_reviews = int(m.split()[1])
ValueError: invalid literal for int() with base 10: '2,539'

```

**Comment by batflyer** [comment]
```python
#file: ffscraper.fanfic.story.py

        for m in metadata:
            if 'Reviews' in m:

                #Previously: num_of_reviews = int(m.split()[1])
                num_of_reviews = int(m.split()[1].replace(',',''))
                users = review.ReviewIDScraper(storyid, num_of_reviews)
                story['Reviewers'] = users

```

**Comment by batflyer** [comment]
Setting issue to resolved.
